; Example configuration
[timers]
workMins = 0
workSeconds = 10

restMins = 0
restSeconds = 10

[text]
startText = Custom timer start message.
workNotification = Custom work message.
restNotification = Custom rest message.

[notification]
enabled = 1
